name: Build Extension ZIP

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version
        id: get_version
        run: echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

      - name: Create ZIP file
        run: |
          # Exclude git, github files, and markdown docs from the final store zip
          zip -r "HaYTooL-StartPage-v${{ steps.get_version.outputs.VERSION }}.zip" . -x "*.git*" -x ".github/*" -x "*.md" -x "LICENSE"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HaYTooL-StartPage-v${{ steps.get_version.outputs.VERSION }}
          path: HaYTooL-StartPage-v${{ steps.get_version.outputs.VERSION }}.zip
          retention-days: 14
